### ISSUE TITLE
Local settings.py pollutes global settings.py?

### ISSUE THREAD

**Issue by caipirginka** [geosolutions-it/django-mapstore-adapter#7]
Please pardon me if this is indeed not a bug, but the following lines:
`PROJECT_NAME = 'mapstore2_adapter'`
`settings.ROOT_URLCONF = '{}.urls'.format(PROJECT_NAME)`

inside the settings.py file seem to pollute the global settings.py file by rewriting the ROOT_URLCONF value.
I'm trying to use Geonode inside another Django project, but this is causing my own urls.py files not be loaded by Django, because the ROOT_URLCONF that I set inside the global settings.py is in fact ignored.
Maybe I'm missing something about the client hook system, but I didn't find a way to make everything work without modifying the above line to set PROJECT_NAME to the name of my own project.

**Comment by afabiani** [comment]
@caipirginka not needed in general for the client hooks, this was actually intentional for the "MapStore" one since we wanted to be able to force the adapter apis URLs to take precedence over the GeoNode ones. See:

```
_urlpatterns = [
    url(r'^mapstore/', include('mapstore2_adapter.api.urls')),
]

try:
    # from geonode.urls import urlpatterns
    app_label = getattr(settings, 'PROJECT_NAME', 'geonode')
    urlpatterns = import_string("%s.urls.urlpatterns" % app_label)
    urlpatterns += _urlpatterns
except BaseException:
    urlpatterns = _urlpatterns
```

You can change the behavior for your specific use case or use another hooksets if this won't fit your needs.
